In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
df = pd.read_csv(r"D:\stock_price_predict\stock_prediction_dataset.csv")
df.head()

,Date,SocialMediaSentiment,FinancialNewsSentiment,BlogSentiment,ForumSentiment,HistoricalStockPrice,StockPrice
0,2020-01-01,Negative,Neutral,Negative,0.208578,118.914515,106.944033
1,2020-01-02,Negative,Positive,Positive,0.140650,100.646310,92.572107
2,2020-01-03,Positive,Positive,Neutral,-0.433726,79.838169,70.305609
3,2020-01-04,Positive,Neutral,Neutral,-0.012673,79.894295,73.258192
4,2020-01-05,Positive,Neutral,Positive,0.279683,118.437172,106.993905

In [6]:
df.shape

(10000, 7)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    10000 non-null  str
 1   SocialMediaSentiment    10000 non-null  str
 2   FinancialNewsSentiment  10000 non-null  str
 3   BlogSentiment           10000 non-null  str
 4   ForumSentiment          10000 non-null  float64
 5   HistoricalStockPrice    10000 non-null  float64
 6   StockPrice              10000 non-null  float64
dtypes: float64(3), str(4)
memory usage: 547.0 KB

In [ ]:
df.isnull().sum()

Index(['Date', 'SocialMediaSentiment', 'FinancialNewsSentiment',
       'BlogSentiment', 'ForumSentiment', 'HistoricalStockPrice',
       'StockPrice'],
      dtype='str')

In [10]:
df.columns

Index(['Date', 'SocialMediaSentiment', 'FinancialNewsSentiment',
       'BlogSentiment', 'ForumSentiment', 'HistoricalStockPrice',
       'StockPrice'],
      dtype='str')

In [16]:
df.describe()

       ForumSentiment  HistoricalStockPrice    StockPrice
count    10000.000000          10000.000000  10000.000000
mean         0.006868            100.599953     90.762524
std          0.576044             28.751821     25.933742
min         -0.999826             50.015776     40.278202
25%         -0.494717             75.941901     68.752997
50%          0.012532            100.601712     90.685550
75%          0.503256            125.557457    113.169407
max          0.999970            149.983526    139.726396

Converting Sentiment Columns to Numbers

Machine learning models cannot understand text like Positive or Negative.

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['SocialMediaSentiment'] = le.fit_transform(df['SocialMediaSentiment'])
df['FinancialNewsSentiment'] = le.fit_transform(df['FinancialNewsSentiment'])
df['BlogSentiment'] = le.fit_transform(df['BlogSentiment'])
df.head()

,Date,SocialMediaSentiment,FinancialNewsSentiment,BlogSentiment,ForumSentiment,HistoricalStockPrice,StockPrice
0,2020-01-01,0,1,0,0.208578,118.914515,106.944033
1,2020-01-02,0,2,2,0.140650,100.646310,92.572107
2,2020-01-03,2,2,1,-0.433726,79.838169,70.305609
3,2020-01-04,2,1,1,-0.012673,79.894295,73.258192
4,2020-01-05,2,1,2,0.279683,118.437172,106.993905